# Generated by Django 4.0.2 on 2022-03-01 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('is_apporved', models.BooleanField(default=False)),
                ('food_group', models.CharField(choices=[('vegetable', 'Vegetable'), ('grain', 'Grain'), ('protein', 'Protien'), ('dairy', 'Dairy'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kid')),
            ],
        ),
    ]
